meta:
  version: 1
  source: "DICOM Toolkit SPEC"
  license: MIT

requirements:
  - id: F-001
    text: The app shall run entirely client-side in a browser with no network requests after initial load.
    rationale: Offline, privacy-first.

  - id: F-002
    text: The project shall build as a static site and deploy to GitHub Pages.
    rationale: Easy hosting.

  - id: F-003
    text: The viewer shall support a configurable multi-viewport layout with drag-to-rearrange and series-to-viewport assignment.
    rationale: Clinical workflows vary.

  - id: F-004
    text: The viewer shall provide MPR for CT/MR volumes with correct spacing/orientation handling.
    rationale: 3D context.

  - id: F-005
    text: The series browser shall display series as a tree with thumbnails, allow rename/remove, and context menu with export/export anonymized/export to video.
    rationale: Discoverability.

  - id: F-006
    text: The anonymizer shall provide Simple mode that filters non-DICOM, anonymizes all DICOM headers using non-deterministic per-session overwrites with a stable mapping, drops images with burned-in PHI, preserves pixel data, and outputs a ZIP.
    rationale: Fast batch anonymization.

  - id: F-007
    text: The anonymizer shall provide Advanced mode with preview, pixel redaction, series selection, and custom overrides for common PHI tags.
    rationale: Granular control.

  - id: F-008
    text: The system shall support ultrasound (multi-frame and single-frame) viewing, anonymization, and export.
    rationale: US is common in practice.

  - id: F-009
    text: The segmentation module shall include brush/erase, threshold, region-growing, and lasso tools.
    rationale: “Smart tools” minimum.

  - id: F-010
    text: The system shall import and export DICOM SEG objects that reference the loaded dataset.
    rationale: Interoperability.

  - id: F-011
    text: The 3D module shall generate meshes from segmentations and export as STL and GLB.
    rationale: Downstream modeling/CAD.

  - id: F-012
    text: The video exporter shall export either a single series or the entire layout at a configurable FPS/resolution/quality, defaulting to H.264 in MKV container when available.
    rationale: Communication.

  - id: F-013
    text: Video export shall allow toggles for overlays, annotations, and a PHI overlay guard defaulting to OFF.
    rationale: Privacy-safe defaults.

  - id: F-014
    text: The UI shall route to the Advanced anonymization workflow from the series browser.
    rationale: Discoverable pathway.

  - id: F-015
    text: The app shall allow drag-and-drop or file picker for loose files, folders, or ZIP inputs; outputs ZIPs for anonymized exports.
    rationale: Usability.

  - id: S-001
    text: The anonymizer shall use cryptographically secure randomness and maintain a per-session stable mapping for overwritten values.
    rationale: True anonymization with referential stability.

  - id: S-002
    text: The app shall hide overlays containing PHI by default and exclude them from exports unless explicitly enabled.
    rationale: Minimize accidental PHI exposure.

  - id: S-003
    text: Advanced mode redacted pixels shall not leak original values in stored artifacts.
    rationale: Prevent PHI leakage.

  - id: N-001
    text: The codebase shall include linting, formatting, and type checks enforced in CI.
    rationale: Maintainability.

  - id: N-002
    text: Test coverage floor shall be >= 80%; mutation testing threshold break < 65%.
    rationale: Test rigor.

  - id: N-003
    text: CI shall fail if source files change in a PR without corresponding test changes.
    rationale: Guard against untested changes.

  - id: N-004
    text: 'A requirements-to-tests traceability check shall fail CI if any requirement ID is not referenced by at least one test via "@req: <ID>" tag.'
    rationale: Spec alignment.

  - id: N-005
    text: The system shall operate without DICOMweb; any HTTP requests to remote hosts are forbidden at runtime.
    rationale: Offline-only constraint.

  # --- UI additions ---

  - id: F-100
    text: Provide a React-based UI shell with a responsive dark theme using CSS variables and Tailwind, defaulting to system preference and persisting user choice.
    rationale: Consistent, accessible, customizable UI foundation.
    notes:
      - Initial CSS variable theme and early bootstrap implemented in site/index.html and site/theme.css; full React shell optional.

  - id: F-101
    text: Expose a theme toggle that is idempotent and persists in localStorage; initial value honors 'prefers-color-scheme'.
    rationale: Usability; respect user/device preference.
    notes:
      - Implemented minimal toggle in site/main.ts (no framework dependency).

  - id: F-102
    text: Implement a Series Browser React component with search, sorting, and context menus for export/anonymize actions.
    rationale: Discoverability and efficient workflows.

  - id: F-103
    text: Implement a Layout Grid React component with drag-and-drop and keyboard reordering that updates a single source of truth.
    rationale: Accessibility and predictability.

  - id: F-104
    text: Implement an Advanced Anonymizer React component that previews redaction rectangles over pixel data without mutating inputs.
    rationale: Safety and clarity.

  - id: F-105
    text: Provide full keyboard navigation for all actionable UI (series list, menus, grid), with visible focus indicators.
    rationale: WCAG 2.1.1 Keyboard; operability.
    notes:
      - Series Browser Up/Down/Enter and Layout Grid Ctrl+Arrow added; visible focus via theme.css.

  - id: F-106
    text: Meet color contrast ≥ 4.5:1 for text and interactive controls in both light and dark themes.
    rationale: WCAG 1.4.3 Contrast (Minimum).

  - id: F-107
    text: Add ARIA roles, names, and states for series items, menus, and grid cells; include live-region toasts for long-running actions.
    rationale: Screen reader support.
    notes:
      - Roles/labels added to Series Browser and Layout; live-region toasts pending.

  - id: F-108
    text: Virtualize long lists (≥ 1,000 series or instances) to keep scroll interactions at 60fps on mid-tier hardware.
    rationale: Performance at scale.

  - id: F-109
    text: Support hash-based routing for deep links to a given study/series and layout preset.
    rationale: Sharable state and reload resilience.
    notes:
      - Layout rows/cols and assignments are encoded/decoded from URL hash in site main demo; deep links to specific series supported via SeriesRef assignments.
      - Full study/series route integration in React shell pending.

  - id: F-110
    text: Persist user settings (theme, last layout, last sort) to localStorage with explicit opt-out.
    rationale: Convenience with privacy.

  - id: F-111
    text: Provide non-blocking progress indicators and errors (toasts/dialogs) for import/export/anonymize flows.
    rationale: Feedback and error recovery.

  - id: N-101
    text: UI shell JavaScript budget ≤ 250 KiB gz (excluding heavy adapters like WebCodecs/vtk/ffmpeg).
    rationale: Fast initial load.

  - id: N-102
    text: First Meaningful Paint ≤ 2s on a 2019 laptop (i5, 8GB) in throttled 3G simulation.
    rationale: Perceived performance.

  - id: N-103
    text: Lighthouse Accessibility score ≥ 90 on main routes.
    rationale: A11y quality bar.

  - id: S-101
    text: UI logs and error surfaces must never include raw DICOM headers or PHI; redact before rendering.
    rationale: Privacy protection.

  - id: S-102
    text: Advanced anonymizer UI must not mutate input buffers; outputs are new arrays with changes.
    rationale: Reproducibility and safety.

  # --- E2E coverage ---

  - id: N-006
    text: End-to-end tests (Playwright) shall cover the main workflows (load/browse, simple anonymize ZIP, advanced anonymizer preview/redaction, segmentation basic ops, SEG import/export, mesh export, video export, MPR and ultrasound viewing) and run headless in CI with screenshots on failure.
    rationale: Verify complete user journeys and prevent regressions.
